// Commission CRUD
export const GET_COMMISSIONS = 'GET_COMMISSIONS';
export const COMMISSIONS_LOADING = 'COMMISSIONS_LOADING';
export const ADD_COMMISSION = 'ADD_COMMISSION';
export const DELETE_COMMISSION = 'DELETE_COMMISSION';